name: Deploy Feature Branch

on:
  push:
    branches:
      - feature/*

jobs:
  package:
    uses: ./.github/workflows/build-and-package.yml
    with:
      environment_name: development
      image_tag_prefix: development
      publish_images: true
    secrets: inherit
